### ISSUE TITLE
still not finished

### ISSUE THREAD

**Issue by Blub124** [sebbi08/TeamMPR-NOSQL#1]

**Comment by sebbi08** [comment]
FUUuUUuuUuUUuu

**Comment by Blub124** [comment]
du hast trotzdem issues!

**Comment by Blub124** [comment]
![sebbi_issue](https://cloud.githubusercontent.com/assets/11698023/10395803/2dee26b4-6e9f-11e5-85aa-066c12df0ae2.PNG)
